# Generated by Django 3.2 on 2024-10-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_apiuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='confirmation_code',
            field=models.IntegerField(default=4124),
        ),
    ]
