# Generated by Django 3.2 on 2024-10-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_apiuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiuser',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь'},
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='confirmation_code',
            field=models.SmallIntegerField(default=3581),
        ),
    ]
