# Generated by Django 3.2 on 2024-10-27 08:12

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20241004_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiuser',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='confirmation_code',
            field=models.SmallIntegerField(default=2994, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с такой почтой уже существует.'}, max_length=254, unique=True, verbose_name='почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Админ')], default='user', max_length=10, verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, max_length=150, unique=True, validators=[users.utils.validate_username], verbose_name='имя пользователя'),
        ),
    ]
