# Generated by Django 3.2 on 2024-10-19 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_alter_reviews_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-pub_date']},
        ),
    ]
