# Generated by Django 3.2 on 2024-10-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_alter_reviews_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reviews',
            name='Оцените произведение от 1 до 10',
        ),
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 1), ('score__lt', 11)), name='Оцените произведение от 1 до 10'),
        ),
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.UniqueConstraint(fields=('title_id', 'author'), name='Только 1 отзыв от пользователя'),
        ),
    ]
