# Generated by Django 3.2 on 2024-10-20 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_auto_20241019_2312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
