# Generated by Django 3.2 on 2024-10-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_alter_title_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('slug',)},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('slug',)},
        ),
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
